version: "3"

# pull back
services:
  nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile
    restart: always
    container_name: nginx
    depends_on:
       - flask
    ports:
      - "80:80"
  flask:
    build:
      context: ./flask
      dockerfile: Dockerfile
    container_name: flask
    stop_signal: SIGINT
    restart: always
    expose:
      - 5000
